# Generated by Django 5.2 on 2025-04-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_deducted', models.FloatField(default=3.0, help_text='Commission (%) for < 90 days')),
                ('interest_earn', models.FloatField(default=4.0, help_text='Interest (%) for ≥ 90 days')),
            ],
            options={
                'verbose_name': 'Finance Setting',
                'verbose_name_plural': 'Finance Settings',
            },
        ),
    ]
