# Generated by Django 5.2 on 2025-04-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='load_eligible_days',
            field=models.CharField(default=45, max_length=3),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='minimum_active_days',
            field=models.CharField(default=45, max_length=3),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='commission_deducted',
            field=models.FloatField(default=3.0, help_text='Commission (%) for < minimum_active_days'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='interest_earn',
            field=models.FloatField(default=4.0, help_text='Interest (%) for ≥ minimum_active_days'),
        ),
    ]
