# Generated by Django 5.2 on 2025-04-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_financesettings_load_eligible_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financesettings',
            name='minimum_active_days',
            field=models.CharField(default=90, max_length=3),
        ),
    ]
