# Generated by Django 5.2 on 2025-04-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_financesettings_minimum_active_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financesettings',
            old_name='load_eligible_days',
            new_name='loan_eligible_days',
        ),
    ]
