# Generated by Django 5.2 on 2025-04-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_load_eligible_days_financesettings_loan_eligible_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='agent_commission_rate',
            field=models.FloatField(default=3.0, help_text='Agent get commission after 1 month'),
        ),
    ]
