# Generated by Django 5.2 on 2025-04-11 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_pan_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingAcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=3, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('eligible_for_loan', models.BooleanField(default=False)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_relation', models.CharField(max_length=50)),
                ('nominee_aadhar', models.CharField(max_length=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_account', to='customers.customer')),
            ],
        ),
    ]
