# Generated by Django 5.2 on 2025-04-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0002_alter_customer_pan_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavingAcount',
            new_name='SavingAccount',
        ),
    ]
