# Generated by Django 5.2 on 2025-04-11 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_savingacount_savingaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingaccount',
            name='start_date',
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 11, 14, 52, 50, 782023, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='last_withdrawal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
