# Generated by Django 5.2 on 2025-04-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_transaction_transaction_type_agentcommission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentcommission',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='agentcommission',
            unique_together=set(),
        ),
    ]
