# Generated by Django 5.2 on 2025-04-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
