"""
Django settings for swarajya_finance project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config
from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY")

DEBUG =config("DEBUG", cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(',')

DATABASES = {
    'default': dj_database_url.parse(config("DATABASE_URL"))  # ✅ FINAL FIX
}

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Bootstrap-styled admin (must be first)
    'users.apps.UsersConfig',   #user app config
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'customers',
    'accounts',
    'core', #settings app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'swarajya_finance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'swarajya_finance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=os.environ.get("DATABASE_URL"))
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  # Always with trailing slash

# This is where Django will collect all static files when you run collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 🚨 must be different from STATICFILES_DIRS

# This is where your project's static files are located (source files)
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # e.g., where your CSS, JS, images live
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Custome Setting
CSRF_TRUSTED_ORIGINS = [
    'https://swarajya-finance.up.railway.app',
]

# frontend theme setting
# or
LOGIN_REDIRECT_URL = '/users/dashboard/'  # if collector login

#admin panel theme setting
LOGIN_REDIRECT_URL = '/admin/'  # for admin

JAZZMIN_SETTINGS = {
    "site_title": "Swarajya Finance Admin",
    "site_header": "Swarajya Finance",
    "site_brand": "Swarajya Finance",
    "welcome_sign": "Welcome to Swarajya Finance Admin Panel",
    "copyright": "Swarajya",
    "search_model": ["users.Profile", "auth.User"],

    # Custom side menu (menu order)
    "order_with_respect_to": ["auth", "core", "customers","accounts"],  # your app order here

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "core.FinanceSettings": "fas fa-cogs",
        "customers.Customer": "fas fa-users-cog",
        "accounts.AgentCommission": "fas fa-money-bill",
        "accounts.SavingAccount": "fas fa-piggy-bank",
        "accounts.Transaction": "fas fa-exchange-alt",
        "users.Profile": "fas fa-user-tie",
    },

    "site_logo": "images/logo.png",
    # "site_logo_classes": "img-circle",
    "login_logo": "images/logo.png",
    "custom_css": "custom_admin.css", 
}
